services:
    quattro_main.admin.taxon:
        class: Quattro\MainBundle\Admin\TaxonAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "main.admin.group.clasify", label: "admin.taxon" }
        arguments:
            - ~
            - Quattro\MainBundle\Entity\Taxon
            - ~
        calls:
            - [ setTranslationDomain, [admin]]
    quattro_main.admin.taxonomy:
        class: Quattro\MainBundle\Admin\TaxonomyAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "main.admin.group.clasify", label: "admin.taxonomy",show_in_dashboard:"false" }
        arguments:
            - ~
            - Quattro\MainBundle\Entity\Taxonomy
            - ~
        calls:
            - [ setTranslationDomain, [admin]]
    quattro_main.admin.tag:
        class: Quattro\MainBundle\Admin\TagAdmin
        arguments: [~, Quattro\MainBundle\Entity\Tag, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "main.admin.group.clasify", label: Tag}
        calls:
            - [ setTranslationDomain, [admin]]
    quattro_main.admin.business:
        class: Quattro\MainBundle\Admin\BusinessAdmin
        arguments: [~, Quattro\MainBundle\Entity\Business, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "main.admin.group.content", label: Business}
        calls:
            - [ setTranslationDomain, [admin]]
    quattro_main.admin.image:
        class: Quattro\MainBundle\Admin\ImageAdmin
        arguments: [~, Quattro\MainBundle\Entity\Image, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "main.admin.group.none", label: Image}
        calls:
            - [ setTranslationDomain, [admin]]